# Generated by Django 5.0.7 on 2024-08-03 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("criminal_index", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="criminal",
            name="default_image",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="criminals_images/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evidence",
            name="file",
            field=models.FileField(upload_to="evidences/"),
        ),
    ]
